development:
  adapter: mysql2
  encoding: utf8
  database: selina_mock_dev
  pool: 5
  username: root
  socket: /var/run/mysqld/mysqld.sock
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: selina_mock_test
  pool: 5
  username: root
  socket: /var/run/mysqld/mysqld.sock
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: selina_mock_production
  pool: 5
  username: root
  socket: /var/run/mysqld/mysqld.sock
